services:
  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        BUILD_CONFIGURATION: Release
#    environment:
#      ASPNETCORE_ENVIRONMENT: Development
#      ASPNETCORE_URLS: http://+:8080
#      ConnectionStrings__DefaultConnection: ${API_CONNECTION_STRING}
#      Cors__AllowedOrigins: ${ALLOWED_ORIGINS}
#      Jwt__Key: ${JWT_KEY}
#      Jwt__Issuer: ${JWT_ISSUER}
#      Jwt__Audience: ${JWT_AUDIENCE}
#      JWT__AccessTokenExpiryMinutes: ${JWT_ACCESS_TOKEN_EXPIRY_MINUTES}
#      JWT__RefreshTokenExpiryDays: ${JWT_REFRESH_TOKEN_EXPIRY_DAYS}
#      CloudinaryUrl: ${CLOUDINARY_URL}
#      Cloudinary__CloudName: ${CLOUDINARY_CLOUD_NAME}
#      Cloudinary__ApiKey: ${CLOUDINARY_API_KEY}
#      Cloudinary__ApiSecret: ${CLOUDINARY_API_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5
#    ports:
#      - "5434:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
